---
swagger: "2.0"
info:
  description: "Elevator Control API"
  version: "1.0.0"
  title: "Lifty"
  contact:
    email: "nelz@orionlabs.io"
basePath: "/v1"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /welcome:
    get:
      summary: "welcome"
      description: "Simple welcome message to verify service is up"
      operationId: "welcome"
      responses:
        200:
          description: "successful connection"
          schema:
            type: "object"
            required:
              - "msg"
            properties:
              msg:
                type: "string"
            additionalProperties: false
  /floor_count:
    get:
      summary: "Number of stops"
      description: "Total number of stops in this elevator"
      operationId: "floorCount"
      responses:
        200:
          description: "count"
          schema:
            type: "object"
            required:
              - "count"
            properties:
              count:
                type: "integer"
                format: "int32"
            additionalProperties: false
  /car/{car_id}/floor/current:
    get:
      summary: "Current Floor"
      description: "What floor is the car currently on"
      operationId: "currentFloor"
      parameters:
        - name: "car_id"
          in: "path"
          description: "The ID of the car we are investigating"
          required: true
          type: "string"
      responses:
        200:
          description: "floor"
          schema:
            type: "object"
            additionalProperties: false
            properties:
              name:
                type: "string"
              id:
                type: "string"
        404:
          description: "Not Found"
  /floor/{floor_id}/car/find:
    get:
      summary: "Find Closest Car"
      description: "Find car closest to specified floor"
      operationId: "findClosestCar"
      parameters:
        - name: "floor_id"
          in: "path"
          description: "The ID of the floor we are investigating"
          required: true
          type: "string"
      responses:
        200:
          description: "closestCar"
          schema:
            type: "object"
            additionalProperties: false
            properties:
              car_id:
                type: "string"
              car_name:
                type: "string"
        404:
          description: "Not Found"
  /floor/{floor_id}/car/call:
    get:
      summary: "Call Closest Car"
      description: "Call closest car to the specified floor"
      operationId: "callClosestCar"
      parameters:
        - name: "floor_id"
          in: "path"
          description: "The ID of the floor we are calling closest car to"
          required: true
          type: "string"
      responses:
        200:
          description: "notify car has arrived"
          schema:
            type: "object"
            additionalProperties: false
            properties:
              msg:
                type: "string"
        404:
          description: "Not Found"
  /admin/inventory/{pwd}:
    get:
      summary: "List Floor and Car IDs"
      description: "Operator Ease-Of-Use: List out Floor and Car identifiers"
      operationId: "inventory"
      parameters:
        - name: "pwd"
          in: "path"
          description: "The password is `p4ssw3rd`"
          required: true
          type: "string"
      responses:
        200:
          description: "count"
          schema:
            type: "array"
            items:
              additionalProperties: false
              type: "object"
              properties:
                car_id:
                  type: "string"
                id:
                  type: "string"
        401:
          description: "not authorized"
